# Generated by Django 2.2 on 2019-07-23 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lfs_lab_cert_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('expiry_in_years', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserInactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Lab User'), (1, 'Principal Investigator')])),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'lab')},
            },
        ),
        migrations.CreateModel(
            name='UserCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_file', models.FileField(upload_to=lfs_lab_cert_tracker.models.create_user_cert_disk_path)),
                ('uploaded_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Cert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cert')},
            },
        ),
        migrations.CreateModel(
            name='LabCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Cert')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Lab')),
            ],
            options={
                'unique_together': {('lab', 'cert')},
            },
        ),
    ]
