# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LabCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Cert')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('cwl', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_path', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('approved_by_user_id', models.IntegerField(null=True)),
                ('completed_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Cert')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.User')),
            ],
        ),
    ]
