# Generated by Django 2.1.2 on 2018-10-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcert',
            old_name='cert',
            new_name='cert_id',
        ),
        migrations.RenameField(
            model_name='labcert',
            old_name='lab',
            new_name='lab_id',
        ),
        migrations.RenameField(
            model_name='userlab',
            old_name='lab',
            new_name='lab_id',
        ),
        migrations.RenameField(
            model_name='userlab',
            old_name='user',
            new_name='user_id',
        ),
    ]
