# Generated by Django 2.2 on 2019-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlab',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Supervisor')]),
        ),
    ]
