# Generated by Django 2.1.2 on 2018-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0002_auto_20181005_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cwl',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
