# Generated by Django 2.1.2 on 2018-10-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0003_auto_20181011_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcert',
            old_name='cert_id',
            new_name='cert',
        ),
        migrations.RenameField(
            model_name='labcert',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='usercert',
            old_name='cert_id',
            new_name='cert',
        ),
        migrations.RenameField(
            model_name='usercert',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlab',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='userlab',
            old_name='user_id',
            new_name='user',
        ),
    ]
