# Generated by Django 4.2.4 on 2023-09-26 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0004_alter_cert_id_alter_lab_id_alter_labcert_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercert',
            unique_together={('user', 'cert', 'completion_date')},
        ),
        migrations.AddField(
            model_name='usercert',
            name='by_api',
            field=models.BooleanField(default=False),
        ),
    ]
