# Generated by Django 4.2 on 2023-06-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0004_alter_cert_id_alter_lab_id_alter_labcert_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=256)),
                ('completion_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
