# Generated by Django 2.1.2 on 2018-10-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0004_auto_20181012_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='cert_path',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='labcert',
            unique_together={('lab', 'cert')},
        ),
        migrations.AlterUniqueTogether(
            name='usercert',
            unique_together={('user', 'cert')},
        ),
        migrations.AlterUniqueTogether(
            name='userlab',
            unique_together={('user', 'lab')},
        ),
    ]
