# Generated by Django 2.1.2 on 2018-10-14 20:21

from django.db import migrations, models
import lfs_lab_cert_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0005_auto_20181013_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercert',
            name='cert_file',
            field=models.FileField(null=True, upload_to=lfs_lab_cert_tracker.models.create_user_cert_disk_path),
        ),
    ]
