# Generated by Django 4.2.7 on 2023-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0005_alter_usercert_unique_together_usercert_by_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256, unique=True)),
                ('lastName', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
