# Generated by Django 4.2.5 on 2024-06-03 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0005_alter_usercert_unique_together_usercert_by_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('affliation', models.CharField(choices=[('0', 'I have a UBC employee ID'), ('1', 'I am an undergraduate student with a UBC student number'), ('2', 'I am a graduate student with a UBC student number'), ('3', 'I do not have a UBC Card. Apply at ubccard.ubc.ca. Access cannot be granted without one.')], default='4', max_length=1)),
                ('employee_number', models.CharField(blank=True, max_length=7, null=True)),
                ('student_number', models.CharField(blank=True, max_length=8, null=True)),
                ('supervisor_first_name', models.CharField(max_length=150)),
                ('supervisor_last_name', models.CharField(max_length=150)),
                ('supervisor_email', models.CharField(max_length=254)),
                ('after_hours_access', models.CharField(choices=[('0', 'Yes, I will need after hours access'), ('1', 'No, I will not need after hours access')], max_length=1)),
                ('working_alone', models.BooleanField(default=False)),
                ('building_name', models.CharField(choices=[('0', 'MCM'), ('1', 'FNH'), ('2', 'WESB'), ('3', 'UBC Farm')], max_length=1)),
                ('room_numbers', models.CharField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lab', 'user'],
            },
        ),
        migrations.AddField(
            model_name='cert',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AccessRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Submitted'), ('1', 'Approved'), ('2', 'Declined')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.accessrequest')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
