# Generated by Django 4.2 on 2023-07-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0005_userapicerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.cert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_certs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
