# Generated by Django 5.1.8 on 2025-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0005_alter_usercert_unique_together_usercert_by_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
