# Generated by Django 2.1.2 on 2018-10-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0006_usercert_cert_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercert',
            name='cert_path',
        ),
    ]
