# Generated by Django 5.2.6 on 2026-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0006_cert_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='is_lfs',
            field=models.BooleanField(default=False),
        ),
    ]
