# Generated by Django 4.2 on 2023-08-04 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0006_missingcert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercert',
            unique_together={('user', 'cert', 'completion_date', 'expiry_date')},
        ),
    ]
