# Generated by Django 4.2.7 on 2023-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0006_keyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='cwl',
            field=models.CharField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='lfsRole',
            field=models.CharField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='ubcEmail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
