# Generated by Django 2.1.2 on 2018-10-14 20:32

from django.db import migrations, models
import lfs_lab_cert_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0007_remove_usercert_cert_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercert',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='usercert',
            name='uploaded_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='approved_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='cert_file',
            field=models.FileField(upload_to=lfs_lab_cert_tracker.models.create_user_cert_disk_path),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
