# Generated by Django 5.2.7 on 2026-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0007_cert_is_lfs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlab',
            options={'ordering': ['role', 'user']},
        ),
        migrations.AlterField(
            model_name='userlab',
            name='role',
            field=models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Supervisor Proxy'), (0, 'User')]),
        ),
    ]
