# Generated by Django 4.2.7 on 2023-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0008_keyrequest_additional_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='building_name',
            field=models.CharField(choices=[('MCM', 'MCM'), ('FNH', 'FNH'), ('WESB', 'WESB'), ('UBC_Farm', 'UBC Farm')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='ubc_affiliation',
            field=models.CharField(choices=[('employee', 'I have a UBC employee ID'), ('undergrad', 'I am an undergraduate student with a UBC student number'), ('grad', 'I am a graduate student with a UBC student number'), ('none', 'I do not have a UBC Card. Apply at ubccard.ubc.ca. Access cannot be granted without one.')], default=None),
            preserve_default=False,
        ),
    ]
