# Generated by Django 2.1.2 on 2018-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0008_auto_20181014_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercert',
            name='approved_by_user_id',
        ),
        migrations.RemoveField(
            model_name='usercert',
            name='approved_date',
        ),
        migrations.AlterField(
            model_name='userlab',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Principal Investigator')]),
        ),
    ]
