# Generated by Django 2.2 on 2019-06-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0009_auto_20181024_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercert',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Invalid'), (3, 'Expired')]),
        ),
    ]
