# Generated by Django 4.2.7 on 2023-12-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0009_keyrequest_building_name_keyrequest_ubc_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='after_hours_access',
            field=models.CharField(choices=[(True, 'Yes, I will need after hours access'), (False, 'No, I will not need after hours access')]),
        ),
    ]
