# Generated by Django 4.2.7 on 2023-12-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0010_alter_keyrequest_after_hours_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='after_hours_access',
            field=models.CharField(choices=[('Yes', 'Yes, I will need after hours access'), ('No', 'No, I will not need after hours access')]),
        ),
    ]
