# Generated by Django 4.2.7 on 2023-12-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0011_alter_keyrequest_after_hours_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='after_hours_access',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='building_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='ubc_affiliation',
            field=models.CharField(),
        ),
    ]
