# Generated by Django 4.2.7 on 2023-12-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_lab_cert_tracker', '0012_alter_keyrequest_after_hours_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='cwl',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='firstName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='lastName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='lfsRole',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='requirement_to_proceed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
