# Generated by Django 2.2 on 2019-06-17 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lfs_lab_cert_tracker', '0013_cert_expiry_in_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlab',
            name='role',
            field=models.IntegerField(choices=[(0, 'Lab User'), (1, 'Principal Investigator')]),
        ),
        migrations.CreateModel(
            name='UserInactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
