import os

# Global variables
DAYS30 = 30
DAYS14 = 14
LFS_LAB_CERT_TRACKER_URL = os.environ['LFS_LAB_CERT_TRACKER_URL']

DATABASE = os.environ['LFS_LAB_CERT_TRACKER_DB_NAME']
USER = os.environ['LFS_LAB_CERT_TRACKER_DB_USER']
PASSWORD = os.environ['LFS_LAB_CERT_TRACKER_DB_PASSWORD']
HOST = os.environ['LFS_LAB_CERT_TRACKER_DB_HOST']
PORT = os.environ['LFS_LAB_CERT_TRACKER_DB_PORT']

SMTP_SERVER = os.environ['LFS_LAB_CERT_TRACKER_EMAIL_HOST']
SENDER = os.environ['LFS_LAB_CERT_TRACKER_EMAIL_FROM']
