# Generated by Django 5.1.4 on 2025-04-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lfs_lab_cert_tracker', '0005_alter_usercert_unique_together_usercert_by_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('affliation', models.CharField(choices=[('0', 'I have a UBC employee ID'), ('1', 'I am an undergraduate student with a UBC student number'), ('2', 'I am a graduate student with a UBC student number'), ('3', 'I do not have a UBC Card. Apply at <a href="https://ubccard.ubc.ca" target="_blank">ubccard.ubc.ca</a>. Access cannot be granted without one.')], default='3', max_length=1)),
                ('employee_number', models.CharField(blank=True, max_length=7, null=True)),
                ('student_number', models.CharField(blank=True, max_length=8, null=True)),
                ('supervisor_first_name', models.CharField(max_length=150)),
                ('supervisor_last_name', models.CharField(max_length=150)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('after_hours_access', models.CharField(choices=[('0', 'Yes, I will need after hours access'), ('1', 'No, I will not need after hours access')], default=None, max_length=1)),
                ('working_alone', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('key', models.BooleanField(default=False)),
                ('fob', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('areas', models.ManyToManyField(to='lfs_lab_cert_tracker.lab')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.floor')),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('trainings', models.ManyToManyField(to='lfs_lab_cert_tracker.cert')),
            ],
            options={
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RequestFormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Approved'), ('1', 'Declined'), ('2', 'Insufficient Info')], default=None, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestformstatus_manager_set', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestformstatus_operator_set', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='requestform',
            name='rooms',
            field=models.ManyToManyField(to='key_request.room'),
        ),
    ]
