# Generated by Django 5.2.7 on 2025-10-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='affliation',
            new_name='affiliation',
        ),
    ]
