# Generated by Django 4.2.15 on 2024-09-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'floor', 'number')},
        ),
    ]
