# Generated by Django 5.1.3 on 2024-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
