# Generated by Django 5.1.3 on 2024-11-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0002_alter_room_unique_together_room_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestformstatus',
            name='comment',
        ),
    ]
