# Generated by Django 5.2.7 on 2025-10-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0002_rename_affliation_requestform_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.floor'),
        ),
    ]
