# Generated by Django 5.1.3 on 2024-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0003_remove_requestformstatus_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
