# Generated by Django 5.2.6 on 2026-05-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0003_alter_room_building_alter_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
