# Generated by Django 4.2.15 on 2024-10-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_request', '0003_alter_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('affliation', models.CharField(choices=[('0', 'I have a UBC employee ID'), ('1', 'I am an undergraduate student with a UBC student number'), ('2', 'I am a graduate student with a UBC student number'), ('3', 'I do not have a UBC Card. Apply at <a href="https://ubccard.ubc.ca" target="_blank">ubccard.ubc.ca</a>. Access cannot be granted without one.')], default='3', max_length=1)),
                ('employee_number', models.CharField(blank=True, max_length=7, null=True)),
                ('student_number', models.CharField(blank=True, max_length=8, null=True)),
                ('supervisor_first_name', models.CharField(max_length=150)),
                ('supervisor_last_name', models.CharField(max_length=150)),
                ('supervisor_email', models.CharField(max_length=254)),
                ('after_hours_access', models.CharField(choices=[('0', 'Yes, I will need after hours access'), ('1', 'No, I will not need after hours access')], default=None, max_length=1)),
                ('working_alone', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.ManyToManyField(to='key_request.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id', '-created_at'],
            },
        ),
    ]
