# Generated by Django 5.2.6 on 2026-07-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0004_remove_requestform_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestformstatus',
            options={'ordering': ['-pk']},
        ),
    ]
