# Generated by Django 4.2.15 on 2024-10-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_request', '0004_keyrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyRequest',
            new_name='Application',
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=254)),
                ('assigned', models.CharField(choices=[('0', 'Applied'), ('1', 'Cancelled'), ('2', 'Insufficient Info'), ('3', 'Accepted'), ('4', 'Declined')], default=None, max_length=1)),
                ('parent_id', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.application')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
