# Generated by Django 5.2.7 on 2026-07-03 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0004_alter_requestform_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Member'), (2, 'Coordinator')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestformstatus_manager_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestformstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestformstatus_group_set', to='key_request.approvalgroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='groups',
            field=models.ManyToManyField(related_name='group_rooms', to='key_request.approvalgroup'),
        ),
        migrations.AddConstraint(
            model_name='requestformstatus',
            constraint=models.CheckConstraint(condition=models.Q(('manager__isnull', False), ('group__isnull', False), _connector='OR'), name='manager_or_group_not_null'),
        ),
        migrations.AddField(
            model_name='approvalgrouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='key_request.approvalgroup'),
        ),
        migrations.AddField(
            model_name='approvalgrouprole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_group_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
