# Generated by Django 5.2.6 on 2026-05-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0004_room_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='overview',
            new_name='note',
        ),
    ]
