# Generated by Django 5.1.4 on 2025-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0004_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='fob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.BooleanField(default=False),
        ),
    ]
