# Generated by Django 5.2.6 on 2026-06-16 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_rename_overview_room_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='supervisor_email',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='supervisor_first_name',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='supervisor_last_name',
        ),
        migrations.AddField(
            model_name='requestform',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_request_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
