# Generated by Django 5.2.7 on 2026-06-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_rename_overview_room_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='managers',
        ),
    ]
