# Generated by Django 5.2.6 on 2026-07-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_alter_requestformstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={'ordering': ['-pk', '-submitted_at']},
        ),
    ]
