# Generated by Django 5.2.7 on 2026-07-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_approvalgroup_approvalgrouprole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestformstatus',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='requestformstatus',
            name='manager_or_group_not_null',
        ),
    ]
