# Generated by Django 4.2.15 on 2024-10-08 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_request', '0005_rename_keyrequest_application_applicationstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='ApplicationStatus',
            new_name='FormStatus',
        ),
    ]
