# Generated by Django 5.2.6 on 2026-07-30 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_approvalgroup_approvalgrouprole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestformstatus',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='requestformstatus',
            name='manager_or_group_not_null',
        ),
        migrations.AddField(
            model_name='approvalgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestformstatus_group_set', to='key_request.approvalgroup'),
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestformstatus_manager_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestformstatus_operator_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
