# Generated by Django 5.2.7 on 2026-05-29 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0005_rename_overview_room_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('members', models.ManyToManyField(related_name='room_groups', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, null=True, to='key_request.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
