# Generated by Django 5.2.6 on 2026-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0006_alter_requestformstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='fob',
            new_name='card_access',
        ),
        migrations.AlterField(
            model_name='roomemail',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
