# Generated by Django 5.2.6 on 2026-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0006_remove_requestform_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
