# Generated by Django 4.2.15 on 2024-10-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0006_rename_application_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formstatus',
            old_name='application',
            new_name='form',
        ),
    ]
