# Generated by Django 5.2.7 on 2026-06-01 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0006_roomgroup'),
        ('lfs_lab_cert_tracker', '0007_cert_is_lfs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('type', models.CharField(choices=[('LAB', 'LabGroup'), ('PAYMENT', 'PaymentGroup')], max_length=50)),
                ('rooms', models.ManyToManyField(blank=True, null=True, to='key_request.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.cert')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.group')),
            ],
            options={
                'unique_together': {('group', 'cert')},
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Supervisor'), (2, 'Supervisor Proxy')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='RoomGroup',
        ),
    ]
