# Generated by Django 5.2.17 on 2026-08-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_rename_fob_room_card_access_alter_roomemail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
