# Generated by Django 5.2.17 on 2026-09-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_rename_fob_room_card_access_alter_roomemail_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='requestform',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestformstatus',
            name='supervisor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Room'), (2, 'Request')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='roomemail',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform'),
        ),
        migrations.AlterField(
            model_name='roomemail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room'),
        ),
        migrations.CreateModel(
            name='RoomExpiryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room')),
            ],
        ),
    ]
