# Generated by Django 5.2.7 on 2026-07-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_approvalgroup_is_active_and_more'),
        ('lfs_lab_cert_tracker', '0007_cert_is_lfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='areas',
        ),
        migrations.CreateModel(
            name='RoomArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_linked', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lfs_lab_cert_tracker.lab')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.room')),
            ],
        ),
    ]
