# Generated by Django 6.1 on 2026-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_rename_fob_room_card_access_alter_roomemail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='supervisor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Room'), (2, 'Request')], default=None, null=True),
        ),
    ]
