# Generated by Django 4.2.15 on 2024-10-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_rename_application_formstatus_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formstatus',
            old_name='assigned',
            new_name='status',
        ),
    ]
