# Generated by Django 5.2.17 on 2026-09-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_rename_fob_room_card_access_alter_roomemail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestformstatus',
            name='supervisor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Room'), (2, 'Request')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='roomemail',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform'),
        ),
        migrations.AlterField(
            model_name='roomemail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room'),
        ),
    ]
