# Generated by Django 5.2.7 on 2026-06-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0007_group_groupcert_usergroup_delete_roomgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['role']},
        ),
    ]
