# Generated by Django 5.2.7 on 2026-06-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0008_alter_usergroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.IntegerField(choices=[(0, 'Supervisor'), (1, 'Supervisor Proxy'), (2, 'User')]),
        ),
    ]
