# Generated by Django 5.2.17 on 2026-09-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0008_requestform_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomemail',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform'),
        ),
        migrations.AlterField(
            model_name='roomemail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room'),
        ),
    ]
