# Generated by Django 4.2.15 on 2024-10-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0008_rename_assigned_formstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formstatus',
            name='operator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='formstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Applied'), ('1', 'Accepted'), ('2', 'Declined'), ('3', 'Cancelled'), ('4', 'Insufficient Info')], default=None, max_length=1),
        ),
    ]
