# Generated by Django 5.2.17 on 2026-09-03 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0008_requestform_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='expiry_date',
        ),
        migrations.CreateModel(
            name='RoomExpiryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='key_request.room')),
            ],
        ),
    ]
