# Generated by Django 5.2.17 on 2026-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0009_roomemail_form_alter_roomemail_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='supervisor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Room'), (2, 'Request')], default=None, null=True),
        ),
    ]
