# Generated by Django 4.2.15 on 2024-10-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0009_formstatus_comment_alter_formstatus_operator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-id', '-submitted_at']},
        ),
        migrations.RenameField(
            model_name='form',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
