# Generated by Django 4.2.15 on 2024-10-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_request', '0010_alter_form_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Submitted'), ('1', 'Approved'), ('2', 'Declined'), ('3', 'Insufficient Info')], default=None, max_length=1)),
                ('operator', models.CharField(blank=True, max_length=254, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RenameModel(
            old_name='Form',
            new_name='RequestForm',
        ),
        migrations.DeleteModel(
            name='FormStatus',
        ),
        migrations.AddField(
            model_name='requestformstatus',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_request.requestform'),
        ),
    ]
