# Generated by Django 4.2.15 on 2024-10-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_request', '0011_requestformstatus_rename_form_requestform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestformstatus',
            name='parent_id',
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
