# Generated by Django 4.2.15 on 2024-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0012_remove_requestformstatus_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='room_id',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Approved'), ('1', 'Declined'), ('2', 'Insufficient Info')], default=None, max_length=1),
        ),
    ]
