# Generated by Django 4.2.15 on 2024-10-21 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0013_requestformstatus_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestformstatus',
            name='operator',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
