# Generated by Django 4.2.15 on 2024-10-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0014_alter_requestformstatus_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestformstatus',
            old_name='operator',
            new_name='operator_id',
        ),
    ]
