# Generated by Django 4.2.15 on 2024-10-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0015_rename_operator_requestformstatus_operator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestformstatus',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
