# Generated by Django 4.2.15 on 2024-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0016_rename_created_at_requestformstatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='manager_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='operator_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestformstatus',
            name='room_id',
            field=models.BigIntegerField(),
        ),
    ]
