# Generated by Django 4.2.15 on 2024-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0017_requestformstatus_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='supervisor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
