# Generated by Django 4.2.15 on 2024-10-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_request', '0018_alter_requestform_supervisor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestformstatus',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
